# Generated by Django 4.2.10 on 2026-03-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snackshop', '0002_alter_category_image_alter_customuser_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_image',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
