# Generated by Django 4.2.10 on 2026-03-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snackshop', '0003_alter_orderitem_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Thanh toán khi nhận hàng'), ('online', 'Thanh toán trực tuyến')], default='cod', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Đang chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('shipping', 'Đang vận chuyển'), ('delivered', 'Đã giao'), ('cancelled', 'Đã hủy')], default='pending', max_length=20),
        ),
    ]
